server:
  port: 8888
  servlet:
    context-path: /api

spring:
  application:
    name: picture-server
  # 激活 local 配置文件
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://14.103.206.253:3306/tt_pictures
    username: root
    password: b1261452095
  # Jackson 时间格式化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    # MyBatis 配置
    #开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射。
    map-underscore-to-camel-case: false
    #仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 指定 Mapper XML 文件位置（标准位置）
  mapper-locations: classpath:mapper/*.xml
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  openapi:
    title: 智能云图库api
    description: ""
    email: longaotian0304@gmail.com
    concat: 龙傲天
    url: https://docs.xiaominfo.com
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.tt.ttpictureserver
