server:
  port: 8888
  servlet:
    context-path: /api

spring:
  application:
    name: picture-server
  # 激活 local 配置文件
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://14.103.206.253:3306/tt_pictures
    username: root
    password: b1261452095
  # Jackson 时间格式化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
  # mq消息队列配置
  rabbitmq:
    host: 14.103.206.253
    port: 5672
    username: admin  # 默认账号
    password: b1261452095  # 默认密码

mybatis-plus:
  configuration:
    # MyBatis 配置
    #开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射。
    map-underscore-to-camel-case: false
    #仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 指定 Mapper XML 文件位置（标准位置）
  mapper-locations: classpath:mapper/*.xml
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  openapi:
    title: 智能云图库api
    description: ""
    email: longaotian0304@gmail.com
    concat: 龙傲天
    url: https://docs.xiaominfo.com
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.tt.ttpictureserver

# 图片删除配置
picture:
  delete:
    # 删除策略: IMMEDIATE(立即删除), SOFT_DELETE(软删除), ASYNC(异步删除)
    strategy: ASYNC
    # 软删除保留天数（仅在 SOFT_DELETE 策略下生效）
    retention-days: 1
    # 定时清理任务 cron 表达式（每天凌晨3点执行）
#    cleanup-cron: "0 0 3 * * ?"
    cleanup-cron: "0 */1 * * * ?"